[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

# Redirect all routes to the Next.js app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables (set these in your Netlify dashboard)
# NEXT_PUBLIC_SUPABASE_URL=your-supabase-url
# NEXT_PUBLIC_SUPABASE_ANON_KEY=your-supabase-anon-key
# SUPABASE_SERVICE_ROLE_KEY=your-service-role-key
# GROQ_API_KEY=your-groq-api-key