# Render Deployment Configuration
version: 1

services:
  - type: web
    name: ai-resume-matcher
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000